GEAR-607 BUG: Fix infinite loop in gear rules
flywheel-apps/GRP-3 pull request #47
Opened 2020-11-17 15:28 UTC by naterichman

* Change type() to isinstance() for pydicom classes that are subclasses of builtins.str
* Add test to make sure string header tags are read

2020-11-17 15:42 UTC, naterichman reviewed
Unfortunately, my linter reformatted these files as well making the changes harder to see.  I left comments on this review where I changed code.   If you want, I can reset these commits and make a new branch without any of the reformatting, let me know.

2020-11-17 15:42 UTC, naterichman commented on tests/unit_tests/test_dicom_to_json.py
> +def test_get_pydicom_header_on_a_real_dicom_and_check_a_few_types(dicom_file):
Changed test file here since MR_small.dcm doesn't come with the repo

2020-11-17 15:42 UTC, naterichman commented on tests/unit_tests/test_dicom_to_json.py
> +    assert isinstance(header["SeriesInstanceUID"], str)
Add check for string header tags

2020-11-17 15:42 UTC, naterichman commented on utils/dicom/dicom_metadata.py
> +                    if (
type() --> isinstance()

2020-11-17 18:00 UTC, NPann requested changes
A few comments left.

2020-11-17 18:00 UTC, NPann commented on tests/unit_tests/test_dicom_to_json.py
> +def test_get_pydicom_header_on_a_real_dicom_and_check_a_few_types(dicom_file):
MR_small is a test file coming from pydicom itself. Should be there.

2020-11-17 18:00 UTC, NPann commented on tests/unit_tests/test_dicom_to_json.py
> +    assert isinstance(header["SeriesInstanceUID"], str)
Can we add a check on an exhaustive list of tags here instead? That's what hit us in that bug, and we allow flagging any header processing discrepencies. dcm -> json -> header. (the json to header transformation will be needed in the metadata toolkit).

2020-11-17 18:00 UTC, NPann commented on utils/dicom/dicom_metadata.py
> +                        type(value) == str and len(value) < 10240
Looking like a code duplicates of `get_pydicom_header`. Unused? If so i'll say let remove give that's buggy.

2020-11-17 18:00 UTC, NPann commented on utils/dicom/dicom_metadata.py
> +                    if (
Is it working because isinstance it asserting type on all parent classes?

2020-11-17 18:04 UTC, NPann commented
> Unfortunately, my linter reformatted these files as well making the changes harder to see. I left comments on this review where I changed code. If you want, I can reset these commits and make a new branch without any of the reformatting, let me know.

Fine to me.

2020-11-17 23:41 UTC, naterichman commented on utils/dicom/dicom_metadata.py
> +                    if (
I believe so. I think type only looks to see if its an instance of the class, and isinstance looks to see if its an instance of a subclass.

2020-11-17 23:42 UTC, naterichman commented on utils/dicom/dicom_metadata.py
> +                        type(value) == str and len(value) < 10240
I'm not sure what you mean here

2020-11-18 04:25 UTC, NPann commented on utils/dicom/dicom_metadata.py
> +                        type(value) == str and len(value) < 10240
I meant that this piece of code in `parse_file_dicom_metadata` seems to be doing the same stuff than the `get_pydicom_header` you have fixed. Not sure what that stuff is doing but given that it has the same `type(value)==str` buggy statement I would remove, especially because it is also likely orphan. Just found about it because of your linting update ;)

2020-11-18 18:32 UTC, NPann approved these changes
LGTM. Approving upfront with the 2 comments above that'll be good to address. Thanks for the quick fix!

2020-11-18 18:32 UTC, NPann commented on Pipfile
> +[[source]]
I would remove the Pipfile and lock files because that's not used in the Dockerfile. It may lead to having local dev env that used the pipenv (which I guess is what this is meant for here) where everything works fine whereas your gear is actually failing because the Dockerfile is using the requirement.txt and you may have some dep discrepencies.

2020-11-18 18:32 UTC, NPann commented on tests/unit_tests/test_dicom_to_json.py
> +# dat.to_csv(str(Path(__file__).parents[1] / "data/dicom_out.csv"))
remove?

2020-11-18 18:32 UTC, NPann commented on tests/data/dicom_out_known_good.json
> +{"ImageType": ["DERIVED", "SECONDARY", "OTHER"], "InstanceCreationDate": "20040826", "InstanceCreationTime": "185434", "InstanceCreatorUID": "1.3.6.1.4.1.5962.3", "SOPClassUID": "1.2.840.10008.5.1.4.
Any chance to use a file with a bit more variation on the header value/type? Concerned by the fact that this one does not have any SQ elements. The CT_small.dcm test file does have 1 SQ element. Might be preferable.

2020-11-18 19:56 UTC, merged